# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2025'
email: opencoraltools@gmail.com
full_name: Charli Forkish
gh_action_docs_preview: true
gh_action_pypi: true
github_org: OpenCoralTools
license: MIT
project_description: Data standards for coral research and conservation
project_name: oct-schema
project_slug: oct_schema

