id: https://w3id.org/OpenCoralTools/oct-schema/classes/Site
name: Site
title: Site Class
description: Represents a physical site

prefixes:
  oct_schema: https://w3id.org/OpenCoralTools/oct-schema/
  linkml: https://w3id.org/linkml/

default_prefix: oct_schema
default_range: string

imports:
  - inventory_record

classes:
  Site:
    is_a: InventoryRecord
    description: Represents a physical site
    slots:
      - site_type_id
      - name
      - group_id_hierarchy
      - description
    slot_usage:
      site_type_id:
        required: true
      name:
        required: true

slots:
  site_type_id:
    range: string
    description: ID of the site type
  group_id_hierarchy:
    range: string
    multivalued: true
    description: Hierarchy of group IDs
